# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waterguard.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='waterguard.proto',
  package='sdf',
  syntax='proto3',
  serialized_pb=_b('\n\x10waterguard.proto\x12\x03sdf\"y\n\x0eTableOperation\x12\x11\n\ttableName\x18\x01 \x01(\t\x12\x14\n\x0c\x66ilterString\x18\x02 \x01(\t\x12\x11\n\tselectors\x18\x03 \x01(\t\x12\x12\n\nnumResults\x18\x04 \x01(\x05\x12\x17\n\x0f\x66ullQueryString\x18\x05 \x01(\t\"k\n\nGenericMap\x12-\n\x07mapping\x18\x01 \x03(\x0b\x32\x1c.sdf.GenericMap.MappingEntry\x1a.\n\x0cMappingEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x88\x01\n\x10WaterGuardUpdate\x12\x11\n\ttableName\x18\x01 \x01(\t\x12\x0f\n\x07rowKeys\x18\x02 \x03(\t\x12(\n\x0fpossibleSensors\x18\x03 \x01(\x0b\x32\x0f.sdf.GenericMap\x12&\n\tquerySpec\x18\x04 \x01(\x0b\x32\x13.sdf.TableOperation\"2\n\x11RequestedReadData\x12\x1d\n\x04rows\x18\x01 \x03(\x0b\x32\x0f.sdf.GenericMap\"s\n\tWriteData\x12!\n\twriteType\x18\x01 \x01(\x0e\x32\x0e.sdf.WriteType\x12$\n\x08location\x18\x02 \x01(\x0e\x32\x12.sdf.WriteLocation\x12\x1d\n\x04rows\x18\x03 \x03(\x0b\x32\x0f.sdf.GenericMap\"\x1d\n\rTwilioMessage\x12\x0c\n\x04\x62ody\x18\x01 \x01(\t*6\n\rWriteLocation\x12\x0f\n\x0bWATCH_TABLE\x10\x00\x12\x14\n\x10SENSOR_BOX_TABLE\x10\x01*/\n\tWriteType\x12\x11\n\rREGULAR_WRITE\x10\x00\x12\x0f\n\x0b\x42\x41TCH_WRITE\x10\x01*\x89\x01\n\x19WaterGuardConfigCallBacks\x12\x14\n\x10\x44UMMY_WGCONFIGCB\x10\x00\x12\x1b\n\x17\x46INISH_SENSORBOX_CONFIG\x10\x01\x12\x1f\n\x1bPROCESS_WATCHTABLE_PRESENCE\x10\x02\x12\x18\n\x14INSERT_LATEST_ROWKEY\x10\x03*a\n\x19WaterGuardSensorCallBacks\x12\x13\n\x0fSET_TOP_ROW_KEY\x10\x00\x12\x15\n\x11QUERY_NEW_ROWKEYS\x10\x01\x12\x18\n\x14PROCESS_READ_RESULTS\x10\x02*M\n\x1aWaterGuardComputeCallBacks\x12\x15\n\x11\x44UMMY_WGCOMPUTECB\x10\x00\x12\x18\n\x14\x43ONFIRM_REGISTRATION\x10\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_WRITELOCATION = _descriptor.EnumDescriptor(
  name='WriteLocation',
  full_name='sdf.WriteLocation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WATCH_TABLE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SENSOR_BOX_TABLE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=596,
  serialized_end=650,
)
_sym_db.RegisterEnumDescriptor(_WRITELOCATION)

WriteLocation = enum_type_wrapper.EnumTypeWrapper(_WRITELOCATION)
_WRITETYPE = _descriptor.EnumDescriptor(
  name='WriteType',
  full_name='sdf.WriteType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REGULAR_WRITE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BATCH_WRITE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=652,
  serialized_end=699,
)
_sym_db.RegisterEnumDescriptor(_WRITETYPE)

WriteType = enum_type_wrapper.EnumTypeWrapper(_WRITETYPE)
_WATERGUARDCONFIGCALLBACKS = _descriptor.EnumDescriptor(
  name='WaterGuardConfigCallBacks',
  full_name='sdf.WaterGuardConfigCallBacks',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DUMMY_WGCONFIGCB', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FINISH_SENSORBOX_CONFIG', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROCESS_WATCHTABLE_PRESENCE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INSERT_LATEST_ROWKEY', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=702,
  serialized_end=839,
)
_sym_db.RegisterEnumDescriptor(_WATERGUARDCONFIGCALLBACKS)

WaterGuardConfigCallBacks = enum_type_wrapper.EnumTypeWrapper(_WATERGUARDCONFIGCALLBACKS)
_WATERGUARDSENSORCALLBACKS = _descriptor.EnumDescriptor(
  name='WaterGuardSensorCallBacks',
  full_name='sdf.WaterGuardSensorCallBacks',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SET_TOP_ROW_KEY', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUERY_NEW_ROWKEYS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROCESS_READ_RESULTS', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=841,
  serialized_end=938,
)
_sym_db.RegisterEnumDescriptor(_WATERGUARDSENSORCALLBACKS)

WaterGuardSensorCallBacks = enum_type_wrapper.EnumTypeWrapper(_WATERGUARDSENSORCALLBACKS)
_WATERGUARDCOMPUTECALLBACKS = _descriptor.EnumDescriptor(
  name='WaterGuardComputeCallBacks',
  full_name='sdf.WaterGuardComputeCallBacks',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DUMMY_WGCOMPUTECB', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONFIRM_REGISTRATION', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=940,
  serialized_end=1017,
)
_sym_db.RegisterEnumDescriptor(_WATERGUARDCOMPUTECALLBACKS)

WaterGuardComputeCallBacks = enum_type_wrapper.EnumTypeWrapper(_WATERGUARDCOMPUTECALLBACKS)
WATCH_TABLE = 0
SENSOR_BOX_TABLE = 1
REGULAR_WRITE = 0
BATCH_WRITE = 1
DUMMY_WGCONFIGCB = 0
FINISH_SENSORBOX_CONFIG = 1
PROCESS_WATCHTABLE_PRESENCE = 2
INSERT_LATEST_ROWKEY = 3
SET_TOP_ROW_KEY = 0
QUERY_NEW_ROWKEYS = 1
PROCESS_READ_RESULTS = 2
DUMMY_WGCOMPUTECB = 0
CONFIRM_REGISTRATION = 1



_TABLEOPERATION = _descriptor.Descriptor(
  name='TableOperation',
  full_name='sdf.TableOperation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tableName', full_name='sdf.TableOperation.tableName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='filterString', full_name='sdf.TableOperation.filterString', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='selectors', full_name='sdf.TableOperation.selectors', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='numResults', full_name='sdf.TableOperation.numResults', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fullQueryString', full_name='sdf.TableOperation.fullQueryString', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=146,
)


_GENERICMAP_MAPPINGENTRY = _descriptor.Descriptor(
  name='MappingEntry',
  full_name='sdf.GenericMap.MappingEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='sdf.GenericMap.MappingEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='sdf.GenericMap.MappingEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=255,
)

_GENERICMAP = _descriptor.Descriptor(
  name='GenericMap',
  full_name='sdf.GenericMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mapping', full_name='sdf.GenericMap.mapping', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_GENERICMAP_MAPPINGENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=255,
)


_WATERGUARDUPDATE = _descriptor.Descriptor(
  name='WaterGuardUpdate',
  full_name='sdf.WaterGuardUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tableName', full_name='sdf.WaterGuardUpdate.tableName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rowKeys', full_name='sdf.WaterGuardUpdate.rowKeys', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='possibleSensors', full_name='sdf.WaterGuardUpdate.possibleSensors', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='querySpec', full_name='sdf.WaterGuardUpdate.querySpec', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=394,
)


_REQUESTEDREADDATA = _descriptor.Descriptor(
  name='RequestedReadData',
  full_name='sdf.RequestedReadData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='sdf.RequestedReadData.rows', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=396,
  serialized_end=446,
)


_WRITEDATA = _descriptor.Descriptor(
  name='WriteData',
  full_name='sdf.WriteData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='writeType', full_name='sdf.WriteData.writeType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='sdf.WriteData.location', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rows', full_name='sdf.WriteData.rows', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=448,
  serialized_end=563,
)


_TWILIOMESSAGE = _descriptor.Descriptor(
  name='TwilioMessage',
  full_name='sdf.TwilioMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='sdf.TwilioMessage.body', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=565,
  serialized_end=594,
)

_GENERICMAP_MAPPINGENTRY.containing_type = _GENERICMAP
_GENERICMAP.fields_by_name['mapping'].message_type = _GENERICMAP_MAPPINGENTRY
_WATERGUARDUPDATE.fields_by_name['possibleSensors'].message_type = _GENERICMAP
_WATERGUARDUPDATE.fields_by_name['querySpec'].message_type = _TABLEOPERATION
_REQUESTEDREADDATA.fields_by_name['rows'].message_type = _GENERICMAP
_WRITEDATA.fields_by_name['writeType'].enum_type = _WRITETYPE
_WRITEDATA.fields_by_name['location'].enum_type = _WRITELOCATION
_WRITEDATA.fields_by_name['rows'].message_type = _GENERICMAP
DESCRIPTOR.message_types_by_name['TableOperation'] = _TABLEOPERATION
DESCRIPTOR.message_types_by_name['GenericMap'] = _GENERICMAP
DESCRIPTOR.message_types_by_name['WaterGuardUpdate'] = _WATERGUARDUPDATE
DESCRIPTOR.message_types_by_name['RequestedReadData'] = _REQUESTEDREADDATA
DESCRIPTOR.message_types_by_name['WriteData'] = _WRITEDATA
DESCRIPTOR.message_types_by_name['TwilioMessage'] = _TWILIOMESSAGE
DESCRIPTOR.enum_types_by_name['WriteLocation'] = _WRITELOCATION
DESCRIPTOR.enum_types_by_name['WriteType'] = _WRITETYPE
DESCRIPTOR.enum_types_by_name['WaterGuardConfigCallBacks'] = _WATERGUARDCONFIGCALLBACKS
DESCRIPTOR.enum_types_by_name['WaterGuardSensorCallBacks'] = _WATERGUARDSENSORCALLBACKS
DESCRIPTOR.enum_types_by_name['WaterGuardComputeCallBacks'] = _WATERGUARDCOMPUTECALLBACKS

TableOperation = _reflection.GeneratedProtocolMessageType('TableOperation', (_message.Message,), dict(
  DESCRIPTOR = _TABLEOPERATION,
  __module__ = 'waterguard_pb2'
  # @@protoc_insertion_point(class_scope:sdf.TableOperation)
  ))
_sym_db.RegisterMessage(TableOperation)

GenericMap = _reflection.GeneratedProtocolMessageType('GenericMap', (_message.Message,), dict(

  MappingEntry = _reflection.GeneratedProtocolMessageType('MappingEntry', (_message.Message,), dict(
    DESCRIPTOR = _GENERICMAP_MAPPINGENTRY,
    __module__ = 'waterguard_pb2'
    # @@protoc_insertion_point(class_scope:sdf.GenericMap.MappingEntry)
    ))
  ,
  DESCRIPTOR = _GENERICMAP,
  __module__ = 'waterguard_pb2'
  # @@protoc_insertion_point(class_scope:sdf.GenericMap)
  ))
_sym_db.RegisterMessage(GenericMap)
_sym_db.RegisterMessage(GenericMap.MappingEntry)

WaterGuardUpdate = _reflection.GeneratedProtocolMessageType('WaterGuardUpdate', (_message.Message,), dict(
  DESCRIPTOR = _WATERGUARDUPDATE,
  __module__ = 'waterguard_pb2'
  # @@protoc_insertion_point(class_scope:sdf.WaterGuardUpdate)
  ))
_sym_db.RegisterMessage(WaterGuardUpdate)

RequestedReadData = _reflection.GeneratedProtocolMessageType('RequestedReadData', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTEDREADDATA,
  __module__ = 'waterguard_pb2'
  # @@protoc_insertion_point(class_scope:sdf.RequestedReadData)
  ))
_sym_db.RegisterMessage(RequestedReadData)

WriteData = _reflection.GeneratedProtocolMessageType('WriteData', (_message.Message,), dict(
  DESCRIPTOR = _WRITEDATA,
  __module__ = 'waterguard_pb2'
  # @@protoc_insertion_point(class_scope:sdf.WriteData)
  ))
_sym_db.RegisterMessage(WriteData)

TwilioMessage = _reflection.GeneratedProtocolMessageType('TwilioMessage', (_message.Message,), dict(
  DESCRIPTOR = _TWILIOMESSAGE,
  __module__ = 'waterguard_pb2'
  # @@protoc_insertion_point(class_scope:sdf.TwilioMessage)
  ))
_sym_db.RegisterMessage(TwilioMessage)


_GENERICMAP_MAPPINGENTRY.has_options = True
_GENERICMAP_MAPPINGENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
