# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wineguard.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wineguard.proto',
  package='sdf',
  syntax='proto3',
  serialized_pb=_b('\n\x0fwineguard.proto\x12\x03sdf\"S\n\x0b\x43redentials\x12\x16\n\x0esubscriptionId\x18\x01 \x01(\t\x12\x15\n\rresourceGroup\x18\x02 \x01(\t\x12\x15\n\rworkspaceName\x18\x03 \x01(\t\"@\n\x07\x44\x61taset\x12\x14\n\x0ctrainingFile\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tlookupKey\x18\x03 \x01(\t\"?\n\x0b\x45nvironment\x12\x10\n\x08localRun\x18\x01 \x01(\x08\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08reqsPath\x18\x03 \x01(\t\"\xb6\x01\n\x0f\x45xperimentSetup\x12\x1d\n\x03\x65nv\x18\x01 \x01(\x0b\x32\x10.sdf.Environment\x12\x16\n\x0e\x65xperimentName\x18\x02 \x01(\t\x12 \n\x06\x61\x63\x63\x65ss\x18\x03 \x01(\x0b\x32\x10.sdf.Credentials\x12\x1d\n\x07\x64\x61taset\x18\x04 \x01(\x0b\x32\x0c.sdf.Dataset\x12\x16\n\x0e\x63omputeCluster\x18\x05 \x01(\t\x12\x13\n\x0b\x65ntryScript\x18\x06 \x01(\t\")\n\x10\x45xperimentResult\x12\x15\n\rresultSummary\x18\x01 \x01(\t*8\n\x10\x43omputeCallBacks\x12\x0f\n\x0b\x44UMMY_FIELD\x10\x00\x12\x13\n\x0fPROCESS_RESULTS\x10\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_COMPUTECALLBACKS = _descriptor.EnumDescriptor(
  name='ComputeCallBacks',
  full_name='sdf.ComputeCallBacks',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DUMMY_FIELD', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROCESS_RESULTS', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=468,
  serialized_end=524,
)
_sym_db.RegisterEnumDescriptor(_COMPUTECALLBACKS)

ComputeCallBacks = enum_type_wrapper.EnumTypeWrapper(_COMPUTECALLBACKS)
DUMMY_FIELD = 0
PROCESS_RESULTS = 1



_CREDENTIALS = _descriptor.Descriptor(
  name='Credentials',
  full_name='sdf.Credentials',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subscriptionId', full_name='sdf.Credentials.subscriptionId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resourceGroup', full_name='sdf.Credentials.resourceGroup', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='workspaceName', full_name='sdf.Credentials.workspaceName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=107,
)


_DATASET = _descriptor.Descriptor(
  name='Dataset',
  full_name='sdf.Dataset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trainingFile', full_name='sdf.Dataset.trainingFile', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='sdf.Dataset.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lookupKey', full_name='sdf.Dataset.lookupKey', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=173,
)


_ENVIRONMENT = _descriptor.Descriptor(
  name='Environment',
  full_name='sdf.Environment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='localRun', full_name='sdf.Environment.localRun', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='sdf.Environment.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reqsPath', full_name='sdf.Environment.reqsPath', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=238,
)


_EXPERIMENTSETUP = _descriptor.Descriptor(
  name='ExperimentSetup',
  full_name='sdf.ExperimentSetup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='env', full_name='sdf.ExperimentSetup.env', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='experimentName', full_name='sdf.ExperimentSetup.experimentName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='access', full_name='sdf.ExperimentSetup.access', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dataset', full_name='sdf.ExperimentSetup.dataset', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='computeCluster', full_name='sdf.ExperimentSetup.computeCluster', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entryScript', full_name='sdf.ExperimentSetup.entryScript', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=423,
)


_EXPERIMENTRESULT = _descriptor.Descriptor(
  name='ExperimentResult',
  full_name='sdf.ExperimentResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resultSummary', full_name='sdf.ExperimentResult.resultSummary', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=466,
)

_EXPERIMENTSETUP.fields_by_name['env'].message_type = _ENVIRONMENT
_EXPERIMENTSETUP.fields_by_name['access'].message_type = _CREDENTIALS
_EXPERIMENTSETUP.fields_by_name['dataset'].message_type = _DATASET
DESCRIPTOR.message_types_by_name['Credentials'] = _CREDENTIALS
DESCRIPTOR.message_types_by_name['Dataset'] = _DATASET
DESCRIPTOR.message_types_by_name['Environment'] = _ENVIRONMENT
DESCRIPTOR.message_types_by_name['ExperimentSetup'] = _EXPERIMENTSETUP
DESCRIPTOR.message_types_by_name['ExperimentResult'] = _EXPERIMENTRESULT
DESCRIPTOR.enum_types_by_name['ComputeCallBacks'] = _COMPUTECALLBACKS

Credentials = _reflection.GeneratedProtocolMessageType('Credentials', (_message.Message,), dict(
  DESCRIPTOR = _CREDENTIALS,
  __module__ = 'wineguard_pb2'
  # @@protoc_insertion_point(class_scope:sdf.Credentials)
  ))
_sym_db.RegisterMessage(Credentials)

Dataset = _reflection.GeneratedProtocolMessageType('Dataset', (_message.Message,), dict(
  DESCRIPTOR = _DATASET,
  __module__ = 'wineguard_pb2'
  # @@protoc_insertion_point(class_scope:sdf.Dataset)
  ))
_sym_db.RegisterMessage(Dataset)

Environment = _reflection.GeneratedProtocolMessageType('Environment', (_message.Message,), dict(
  DESCRIPTOR = _ENVIRONMENT,
  __module__ = 'wineguard_pb2'
  # @@protoc_insertion_point(class_scope:sdf.Environment)
  ))
_sym_db.RegisterMessage(Environment)

ExperimentSetup = _reflection.GeneratedProtocolMessageType('ExperimentSetup', (_message.Message,), dict(
  DESCRIPTOR = _EXPERIMENTSETUP,
  __module__ = 'wineguard_pb2'
  # @@protoc_insertion_point(class_scope:sdf.ExperimentSetup)
  ))
_sym_db.RegisterMessage(ExperimentSetup)

ExperimentResult = _reflection.GeneratedProtocolMessageType('ExperimentResult', (_message.Message,), dict(
  DESCRIPTOR = _EXPERIMENTRESULT,
  __module__ = 'wineguard_pb2'
  # @@protoc_insertion_point(class_scope:sdf.ExperimentResult)
  ))
_sym_db.RegisterMessage(ExperimentResult)


# @@protoc_insertion_point(module_scope)
