# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actuation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import shared_pb2 as shared__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='actuation.proto',
  package='sdf',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x61\x63tuation.proto\x12\x03sdf\x1a\x0cshared.proto\"L\n\x0c\x41\x63tuationRPC\x12%\n\tprocedure\x18\x01 \x01(\x0b\x32\x12.sdf.ProcedureType\x12\x15\n\rproc_commands\x18\x02 \x01(\x0c\x62\x06proto3')
  ,
  dependencies=[shared__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ACTUATIONRPC = _descriptor.Descriptor(
  name='ActuationRPC',
  full_name='sdf.ActuationRPC',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='procedure', full_name='sdf.ActuationRPC.procedure', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='proc_commands', full_name='sdf.ActuationRPC.proc_commands', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=114,
)

_ACTUATIONRPC.fields_by_name['procedure'].message_type = shared__pb2._PROCEDURETYPE
DESCRIPTOR.message_types_by_name['ActuationRPC'] = _ACTUATIONRPC

ActuationRPC = _reflection.GeneratedProtocolMessageType('ActuationRPC', (_message.Message,), dict(
  DESCRIPTOR = _ACTUATIONRPC,
  __module__ = 'actuation_pb2'
  # @@protoc_insertion_point(class_scope:sdf.ActuationRPC)
  ))
_sym_db.RegisterMessage(ActuationRPC)


# @@protoc_insertion_point(module_scope)
