# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compute.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import shared_pb2 as shared__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='compute.proto',
  package='sdf',
  syntax='proto3',
  serialized_pb=_b('\n\rcompute.proto\x12\x03sdf\x1a\x0cshared.proto\"V\n\nComputeRPC\x12%\n\tprocedure\x18\x01 \x01(\x0b\x32\x12.sdf.ProcedureType\x12\x11\n\tproc_args\x18\x02 \x01(\x0c\x12\x0e\n\x06update\x18\x03 \x01(\x0c\x62\x06proto3')
  ,
  dependencies=[shared__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COMPUTERPC = _descriptor.Descriptor(
  name='ComputeRPC',
  full_name='sdf.ComputeRPC',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='procedure', full_name='sdf.ComputeRPC.procedure', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='proc_args', full_name='sdf.ComputeRPC.proc_args', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='update', full_name='sdf.ComputeRPC.update', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=122,
)

_COMPUTERPC.fields_by_name['procedure'].message_type = shared__pb2._PROCEDURETYPE
DESCRIPTOR.message_types_by_name['ComputeRPC'] = _COMPUTERPC

ComputeRPC = _reflection.GeneratedProtocolMessageType('ComputeRPC', (_message.Message,), dict(
  DESCRIPTOR = _COMPUTERPC,
  __module__ = 'compute_pb2'
  # @@protoc_insertion_point(class_scope:sdf.ComputeRPC)
  ))
_sym_db.RegisterMessage(ComputeRPC)


# @@protoc_insertion_point(module_scope)
