# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dairymgr.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from .generated.vendorone import vendor_one_pb2 as vendor__one__pb2
from .generated.vendortwo import vendor_two_pb2 as vendor__two__pb2
from .generated.vendorthree import vendor_three_pb2 as vendor__three__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dairymgr.proto',
  package='dairymgr',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x64\x61irymgr.proto\x12\x08\x64\x61irymgr\x1a\x10vendor_one.proto\x1a\x10vendor_two.proto\x1a\x12vendor_three.proto\"\xb0\x01\n\rFarmPCMessage\x12-\n\tvendorOne\x18\x01 \x01(\x0b\x32\x18.dairymgr.VendorOneEntryH\x00\x12-\n\tvendorTwo\x18\x02 \x01(\x0b\x32\x18.dairymgr.VendorTwoEntryH\x00\x12\x31\n\x0bvendorThree\x18\x03 \x01(\x0b\x32\x1a.dairymgr.VendorThreeEntryH\x00\x42\x0e\n\x0c\x66\x61rmpc_types*@\n\x17\x44\x61iryMgrSensorCallBacks\x12\x12\n\x0e\x43\x41LL_ZERO_HERE\x10\x00\x12\x11\n\rCALL_ONE_HERE\x10\x01*K\n\x18\x44\x61iryMgrComputeCallBacks\x12\x18\n\x14\x43ONFIRM_REGISTRATION\x10\x00\x12\x15\n\x11PROCESS_READ_DATA\x10\x01\x62\x06proto3')
  ,
  dependencies=[vendor__one__pb2.DESCRIPTOR,vendor__two__pb2.DESCRIPTOR,vendor__three__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_DAIRYMGRSENSORCALLBACKS = _descriptor.EnumDescriptor(
  name='DairyMgrSensorCallBacks',
  full_name='dairymgr.DairyMgrSensorCallBacks',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CALL_ZERO_HERE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CALL_ONE_HERE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=263,
  serialized_end=327,
)
_sym_db.RegisterEnumDescriptor(_DAIRYMGRSENSORCALLBACKS)

DairyMgrSensorCallBacks = enum_type_wrapper.EnumTypeWrapper(_DAIRYMGRSENSORCALLBACKS)
_DAIRYMGRCOMPUTECALLBACKS = _descriptor.EnumDescriptor(
  name='DairyMgrComputeCallBacks',
  full_name='dairymgr.DairyMgrComputeCallBacks',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONFIRM_REGISTRATION', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROCESS_READ_DATA', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=329,
  serialized_end=404,
)
_sym_db.RegisterEnumDescriptor(_DAIRYMGRCOMPUTECALLBACKS)

DairyMgrComputeCallBacks = enum_type_wrapper.EnumTypeWrapper(_DAIRYMGRCOMPUTECALLBACKS)
CALL_ZERO_HERE = 0
CALL_ONE_HERE = 1
CONFIRM_REGISTRATION = 0
PROCESS_READ_DATA = 1



_FARMPCMESSAGE = _descriptor.Descriptor(
  name='FarmPCMessage',
  full_name='dairymgr.FarmPCMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vendorOne', full_name='dairymgr.FarmPCMessage.vendorOne', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vendorTwo', full_name='dairymgr.FarmPCMessage.vendorTwo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vendorThree', full_name='dairymgr.FarmPCMessage.vendorThree', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='farmpc_types', full_name='dairymgr.FarmPCMessage.farmpc_types',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=85,
  serialized_end=261,
)

_FARMPCMESSAGE.fields_by_name['vendorOne'].message_type = vendor__one__pb2._VENDORONEENTRY
_FARMPCMESSAGE.fields_by_name['vendorTwo'].message_type = vendor__two__pb2._VENDORTWOENTRY
_FARMPCMESSAGE.fields_by_name['vendorThree'].message_type = vendor__three__pb2._VENDORTHREEENTRY
_FARMPCMESSAGE.oneofs_by_name['farmpc_types'].fields.append(
  _FARMPCMESSAGE.fields_by_name['vendorOne'])
_FARMPCMESSAGE.fields_by_name['vendorOne'].containing_oneof = _FARMPCMESSAGE.oneofs_by_name['farmpc_types']
_FARMPCMESSAGE.oneofs_by_name['farmpc_types'].fields.append(
  _FARMPCMESSAGE.fields_by_name['vendorTwo'])
_FARMPCMESSAGE.fields_by_name['vendorTwo'].containing_oneof = _FARMPCMESSAGE.oneofs_by_name['farmpc_types']
_FARMPCMESSAGE.oneofs_by_name['farmpc_types'].fields.append(
  _FARMPCMESSAGE.fields_by_name['vendorThree'])
_FARMPCMESSAGE.fields_by_name['vendorThree'].containing_oneof = _FARMPCMESSAGE.oneofs_by_name['farmpc_types']
DESCRIPTOR.message_types_by_name['FarmPCMessage'] = _FARMPCMESSAGE
DESCRIPTOR.enum_types_by_name['DairyMgrSensorCallBacks'] = _DAIRYMGRSENSORCALLBACKS
DESCRIPTOR.enum_types_by_name['DairyMgrComputeCallBacks'] = _DAIRYMGRCOMPUTECALLBACKS

FarmPCMessage = _reflection.GeneratedProtocolMessageType('FarmPCMessage', (_message.Message,), dict(
  DESCRIPTOR = _FARMPCMESSAGE,
  __module__ = 'dairymgr_pb2'
  # @@protoc_insertion_point(class_scope:dairymgr.FarmPCMessage)
  ))
_sym_db.RegisterMessage(FarmPCMessage)


# @@protoc_insertion_point(module_scope)
